version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  #   links:
  #     - mongo
  # mongo:
  #   image: mongo:3.0.4
  #   ports:
  #     - "27017:27017"
  #   volumes_from:
  #     - mongodata
  #   command: --smallfiles --rest
  # mongodata:
  #    image: mongo:3.0.4
  #    volumes:
  #      - /data/db
  #    command: --break-mongo
